"""Public runtime composition and workflow-control facades."""

from typing import TYPE_CHECKING

from justflow.config.settings import ScheduledStartWorkloadClass
from justflow.runtime.admin_panel import AdminPanel, AdminPanelAsset
from justflow.runtime.api_compatibility import (
    MAXIMUM_SUPPORTED_CLIENT_VERSION as MAXIMUM_SUPPORTED_CLIENT_VERSION,
)
from justflow.runtime.api_compatibility import (
    MINIMUM_SUPPORTED_CLIENT_VERSION as MINIMUM_SUPPORTED_CLIENT_VERSION,
)
from justflow.runtime.api_compatibility import (
    PUBLIC_API_COMPATIBILITY as PUBLIC_API_COMPATIBILITY,
)
from justflow.runtime.api_compatibility import (
    PUBLIC_API_COMPATIBILITY_VERSION as PUBLIC_API_COMPATIBILITY_VERSION,
)
from justflow.runtime.api_compatibility import ApiCompatibility as ApiCompatibility
from justflow.runtime.auth import (
    AuthenticatedPrincipal,
    AuthenticationError,
    AuthenticationProvider,
    AuthenticationRequest,
    AuthorizationAction,
    AuthorizationRequest,
    authorization_resource_digest,
)
from justflow.runtime.cloud_events import (
    CloudEventErrorCode,
    CloudEventIngress,
    CloudEventMapper,
    CloudEventMappingError,
    CloudEventMappingRegistry,
    CloudEventMetadata,
    CloudEventPayloadError,
    EventBridgeEnvelope,
    EventBridgeEventMapper,
    EventBridgeWorkflowEvent,
    S3ObjectCreatedEventMapper,
    S3ObjectCreatedWorkflowEvent,
    S3ObjectKeyFilter,
    make_cloud_event_business_request_id,
)
from justflow.runtime.configuration_activation import (
    ActivationControllerError,
    ActivationPreparationSource,
    ConfigurationActivationController,
    DefinitionCatalogSource,
    ExternalOperationConfirmation,
    PreparedActivation,
    PreparedRuntimeIndex,
    PreparedWorkerDeployment,
    ReconcilerScheduleActivationBinding,
    RuntimeIndexSnapshot,
    ScheduleActivationBinding,
    ScopedDefinitionCatalogSource,
    WorkerDeploymentBinding,
    WorkerDeploymentObservation,
    WorkerDeploymentRetirement,
)
from justflow.runtime.configuration_api import ConfigurationApi
from justflow.runtime.control_api import ControlApi
from justflow.runtime.health import (
    ComponentHealth,
    HealthComponent,
    HealthReason,
    HealthRegistry,
    HealthReport,
    HealthStatus,
)
from justflow.runtime.metrics import (
    ActivationMetricState,
    MetricsRegistry,
    ScheduledStartMetricOutcome,
    ScheduleMetricOperation,
    ScheduleMetricOutcome,
)
from justflow.runtime.operations import (
    ContinuationChain,
    ControlErrorCode,
    ControlOperationError,
    PendingWait,
    PendingWaitKind,
    WorkflowControlService,
    WorkflowDescription,
    WorkflowExecutionState,
    WorkflowFailureClassification,
    WorkflowListQuery,
    WorkflowListResult,
    WorkflowSummary,
)
from justflow.runtime.operations_api import (
    OperationsApi,
    OperationsApiRequestError,
    OperationsApiResponse,
    OperationsRoute,
    OperationsRouteKind,
)
from justflow.runtime.operations_query import (
    ActivationOperationsView,
    ConfigurationOperationsView,
    ConfigurationSchema,
    DefinitionPage,
    DefinitionSummary,
    MetricsLink,
    OperationsAvailability,
    OperationsDimension,
    OperationsOverview,
    OperationsQueryError,
    OperationsQueryErrorCode,
    OperationsQueryService,
    ScopedDeclaredTriggerSource,
    ScopedScheduleOperationsSource,
    TriggerOperationalState,
    TriggerOperationsView,
    TriggerSummary,
    WorkflowRegistration,
    WorkflowRegistrationPage,
)
from justflow.runtime.schedule_operations import (
    BoundScheduleControlService,
    ManagedScheduleDescription,
    ScheduleControlService,
    ScheduleOperationError,
    ScheduleOperationErrorCode,
    ScheduleOperator,
    ScheduleRecentAction,
    ScopedScheduleControlService,
    TriggerRunNowStatus,
)
from justflow.runtime.schedule_reconciler import (
    ScheduleApplyErrorCode,
    ScheduleApplyItem,
    ScheduleApplyResult,
    ScheduleApplyStatus,
    ScheduleReconciler,
    ScheduleReconciliationError,
    ScheduleReconciliationErrorCode,
)
from justflow.runtime.scheduled_start_service import (
    ScheduledStartDecisionRecorder,
    ScheduledStartQuotaController,
    ScheduledStartService,
    ScheduledStartWorkloadPolicy,
)
from justflow.runtime.scheduled_starts import (
    ScheduledStartCancelRequest,
    ScheduledStartCreateRequest,
    ScheduledStartDescription,
    ScheduledStartError,
    ScheduledStartErrorCode,
    ScheduledStartFailureCode,
    ScheduledStartMutationResult,
    ScheduledStartMutationStatus,
    ScheduledStartPage,
    ScheduledStartRescheduleRequest,
    ScheduledStartState,
)
from justflow.runtime.schedules import (
    DesiredSchedule,
    ObservedSchedule,
    ScheduleChange,
    ScheduleChangeKind,
    ScheduleDispatchPlan,
    SchedulePlan,
    ScheduleTargetIdentity,
    UnscopedScheduleDecision,
    make_schedule_run_now_workflow_id,
)
from justflow.runtime.starter import (
    BrokerSourceIdentity,
    CloudEventSourceIdentity,
    ControlApiSourceIdentity,
    HostSourceIdentity,
    ScheduleSourceIdentity,
    ScopedWorkflowTargetResolver,
    StartErrorCode,
    StartStatus,
    StartWorkflowRequest,
    StartWorkflowResult,
    TriggerSource,
    WebhookSourceIdentity,
    WorkflowStarter,
    WorkflowStartError,
    WorkflowTargetResolver,
)
from justflow.runtime.temporal import (
    TemporalConnectionBinding,
    TemporalConnectionConfigurationError,
    TemporalConnectionError,
    TemporalConnectionPolicy,
    resolve_temporal_connection,
)
from justflow.runtime.webhooks import (
    SignedWebhookRequest,
    WebhookError,
    WebhookErrorCode,
    WebhookEventIdentity,
    WebhookIngress,
    WebhookPayloadError,
    WebhookSourceAdapter,
    WebhookSourceRegistry,
    WebhookVerificationError,
    make_webhook_business_request_id,
)
from justflow.scope import (
    LOCAL_RUNTIME_SCOPE,
    ApplicationIdentity,
    EnvironmentIdentity,
    RuntimeScope,
    ScopeBindingKind,
    ScopeResolutionError,
    TenantIdentity,
    TrustedScopeBinding,
)

if TYPE_CHECKING:
    from justflow.runtime.application import (
        RuntimeApplication,
        RuntimeAsgiApplication,
        RuntimeGateway,
        WorkerAsgiApplication,
    )

__all__ = [
    "LOCAL_RUNTIME_SCOPE",
    "ActivationControllerError",
    "ActivationMetricState",
    "ActivationOperationsView",
    "ActivationPreparationSource",
    "AdminPanel",
    "AdminPanelAsset",
    "ApplicationIdentity",
    "AuthenticatedPrincipal",
    "AuthenticationError",
    "AuthenticationProvider",
    "AuthenticationRequest",
    "AuthorizationAction",
    "AuthorizationRequest",
    "BoundScheduleControlService",
    "BrokerSourceIdentity",
    "CloudEventErrorCode",
    "CloudEventIngress",
    "CloudEventMapper",
    "CloudEventMappingError",
    "CloudEventMappingRegistry",
    "CloudEventMetadata",
    "CloudEventPayloadError",
    "CloudEventSourceIdentity",
    "ComponentHealth",
    "ConfigurationActivationController",
    "ConfigurationApi",
    "ConfigurationOperationsView",
    "ConfigurationSchema",
    "ContinuationChain",
    "ControlApi",
    "ControlApiSourceIdentity",
    "ControlErrorCode",
    "ControlOperationError",
    "DefinitionCatalogSource",
    "DefinitionPage",
    "DefinitionSummary",
    "DesiredSchedule",
    "EnvironmentIdentity",
    "EventBridgeEnvelope",
    "EventBridgeEventMapper",
    "EventBridgeWorkflowEvent",
    "ExternalOperationConfirmation",
    "HealthComponent",
    "HealthReason",
    "HealthRegistry",
    "HealthReport",
    "HealthStatus",
    "HostSourceIdentity",
    "ManagedScheduleDescription",
    "MetricsLink",
    "MetricsRegistry",
    "ObservedSchedule",
    "OperationsApi",
    "OperationsApiRequestError",
    "OperationsApiResponse",
    "OperationsAvailability",
    "OperationsDimension",
    "OperationsOverview",
    "OperationsQueryError",
    "OperationsQueryErrorCode",
    "OperationsQueryService",
    "OperationsRoute",
    "OperationsRouteKind",
    "PendingWait",
    "PendingWaitKind",
    "PreparedActivation",
    "PreparedRuntimeIndex",
    "PreparedWorkerDeployment",
    "ReconcilerScheduleActivationBinding",
    "RuntimeApplication",
    "RuntimeAsgiApplication",
    "RuntimeGateway",
    "RuntimeIndexSnapshot",
    "RuntimeScope",
    "S3ObjectCreatedEventMapper",
    "S3ObjectCreatedWorkflowEvent",
    "S3ObjectKeyFilter",
    "ScheduleActivationBinding",
    "ScheduleApplyErrorCode",
    "ScheduleApplyItem",
    "ScheduleApplyResult",
    "ScheduleApplyStatus",
    "ScheduleChange",
    "ScheduleChangeKind",
    "ScheduleControlService",
    "ScheduleDispatchPlan",
    "ScheduleMetricOperation",
    "ScheduleMetricOutcome",
    "ScheduleOperationError",
    "ScheduleOperationErrorCode",
    "ScheduleOperator",
    "SchedulePlan",
    "ScheduleRecentAction",
    "ScheduleReconciler",
    "ScheduleReconciliationError",
    "ScheduleReconciliationErrorCode",
    "ScheduleRuntime",
    "ScheduleSourceIdentity",
    "ScheduleTargetIdentity",
    "ScheduledStartCancelRequest",
    "ScheduledStartCreateRequest",
    "ScheduledStartDecisionRecorder",
    "ScheduledStartDescription",
    "ScheduledStartError",
    "ScheduledStartErrorCode",
    "ScheduledStartFailureCode",
    "ScheduledStartMetricOutcome",
    "ScheduledStartMutationResult",
    "ScheduledStartMutationStatus",
    "ScheduledStartPage",
    "ScheduledStartQuotaController",
    "ScheduledStartRescheduleRequest",
    "ScheduledStartService",
    "ScheduledStartState",
    "ScheduledStartWorkloadClass",
    "ScheduledStartWorkloadPolicy",
    "ScopeBindingKind",
    "ScopeResolutionError",
    "ScopedDeclaredTriggerSource",
    "ScopedDefinitionCatalogSource",
    "ScopedScheduleControlService",
    "ScopedScheduleOperationsSource",
    "ScopedWorkflowTargetResolver",
    "SignedWebhookRequest",
    "StartErrorCode",
    "StartStatus",
    "StartWorkflowRequest",
    "StartWorkflowResult",
    "TemporalConnectionBinding",
    "TemporalConnectionConfigurationError",
    "TemporalConnectionError",
    "TemporalConnectionPolicy",
    "TenantIdentity",
    "TriggerOperationalState",
    "TriggerOperationsView",
    "TriggerRunNowStatus",
    "TriggerSource",
    "TriggerSummary",
    "TrustedScopeBinding",
    "UnscopedScheduleDecision",
    "WebhookError",
    "WebhookErrorCode",
    "WebhookEventIdentity",
    "WebhookIngress",
    "WebhookPayloadError",
    "WebhookSourceAdapter",
    "WebhookSourceIdentity",
    "WebhookSourceRegistry",
    "WebhookVerificationError",
    "WorkerAsgiApplication",
    "WorkerDeploymentBinding",
    "WorkerDeploymentObservation",
    "WorkerDeploymentRetirement",
    "WorkflowControlService",
    "WorkflowDescription",
    "WorkflowExecutionState",
    "WorkflowFailureClassification",
    "WorkflowListQuery",
    "WorkflowListResult",
    "WorkflowRegistration",
    "WorkflowRegistrationPage",
    "WorkflowStartError",
    "WorkflowStarter",
    "WorkflowSummary",
    "WorkflowTargetResolver",
    "authorization_resource_digest",
    "make_cloud_event_business_request_id",
    "make_schedule_run_now_workflow_id",
    "make_webhook_business_request_id",
    "resolve_temporal_connection",
]


def __getattr__(name: str) -> object:
    if name in {
        "RuntimeApplication",
        "RuntimeAsgiApplication",
        "RuntimeGateway",
        "ScheduleRuntime",
        "WorkerAsgiApplication",
    }:
        from justflow.runtime.application import (
            RuntimeApplication,
            RuntimeAsgiApplication,
            RuntimeGateway,
            WorkerAsgiApplication,
        )

        applications: dict[str, object] = {
            "RuntimeApplication": RuntimeApplication,
            "RuntimeAsgiApplication": RuntimeAsgiApplication,
            "RuntimeGateway": RuntimeGateway,
            "WorkerAsgiApplication": WorkerAsgiApplication,
        }
        if name == "ScheduleRuntime":
            from justflow.runtime.schedule_application import ScheduleRuntime

            return ScheduleRuntime
        return applications[name]
    raise AttributeError(name)
