"""Resource provider facade and built-in registrations."""

from justflow.resources.base import (
    ArchiveStore,
    CacheStore,
    ConfigReader,
    ConfiguredResource,
    Database,
    KeyValueStore,
    ManagedResource,
    ObjectStore,
    ResourceCapability,
    ResourceDependency,
    ResourceError,
    ResourceFactoryContext,
    SecretReader,
    StrictResourceConfig,
)
from justflow.resources.builtins import builtin_resource_registry
from justflow.resources.registry import (
    DuplicateResourceProviderError,
    ResourceClassImportError,
    ResourceCollection,
    ResourceConfigError,
    ResourceDependencyError,
    ResourceGrant,
    ResourceProvider,
    ResourceRegistry,
    ResourceRegistryError,
    UnknownResourceProviderError,
)

__all__ = [
    "ArchiveStore",
    "CacheStore",
    "ConfigReader",
    "ConfiguredResource",
    "Database",
    "DuplicateResourceProviderError",
    "KeyValueStore",
    "ManagedResource",
    "ObjectStore",
    "ResourceCapability",
    "ResourceClassImportError",
    "ResourceCollection",
    "ResourceConfigError",
    "ResourceDependency",
    "ResourceDependencyError",
    "ResourceError",
    "ResourceFactoryContext",
    "ResourceGrant",
    "ResourceProvider",
    "ResourceRegistry",
    "ResourceRegistryError",
    "SecretReader",
    "StrictResourceConfig",
    "UnknownResourceProviderError",
    "builtin_resource_registry",
]
